server:
  port: 20084


spring:
  application:
    #服务名
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        #nacos注册中心的地址
        server-addr: localhost:8848
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719

      datasource:
        ds1:
          nacos:
            #nacos的地址
            server-addr: localhost:8848
            #nacos配置文件所在的名称空间
            namespace: 300557ef-a705-4e9a-8126-105baf77279f
            #nacos配置文件所在的组
            groupId: GROUP0001
            #nacos的配置文件名称
            dataId: cloud-alibaba-sentinel-service
            #配置文件的名称后缀
            data-type: json
            #指明这个是流控、还是降级、热点key等规则
            rule-type: flow


# 激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true