server:
  port: 2002

spring:
  application:
    name: seata-storage-service

  cloud:
    alibaba:
      #seata相关配置
      seata:
        # 自定义事务组  Seata 事务组编号，用于 TC 集群名
        tx-service-group: my_tx_group


    nacos:
      discovery:
        #nacos注册地址
        server-addr: localhost:8848
      config:
        #nacos配置中心地址
        server-addr: localhost:8848

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_storage
    username: root
    password: wskzxw

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml


