server:
  port: 12004

spring:
  application:
    name: cloud-sleuth-zipkin12004


  zipkin:
    ## zipkin server 的请求地址
    base-url: http://localhost:9411
    sleuth:
      sampler:
        #采样率值介于 0 到 1 之间，数字越大，采集的信息越全面，但也越耗时，1 则表示全部采集
        probability: 1.0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #集群
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
