server:
  port: 14001


spring:
  application:
    #服务名称
    name: cloudAlibaba-order-consumer14001

  cloud:
    nacos:
      discovery:
        # 注册到nacos注册中心，这里是nacos的地址
        server-addr: localhost:8848


#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
service-url:
  nacos-user-service: http://cloudAlibaba-payment-provider