server:
  port: 10200

# 服务名称
spring:
  application:
    name: cloud-sale-service


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #集群
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
