server:
  port: 2001

spring:
  application:
    #服务名称
    name: seata-order-service
  cloud:
    alibaba:
      #seata相关配置
      seata:
        # 自定义事务组  Seata 事务组编号，用于 TC 集群名
        tx-service-group: my_tx_group


    nacos:
      discovery:
        #nacos注册地址
        server-addr: localhost:8848
      config:
        #nacos配置中心地址
        server-addr: localhost:8848

  #数据库相关配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order?serverTimezone=Asia/Shanghai
    username: root
    password: wskzxw

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml
