# 服务启动端口号
server:
  port: 80

# 服务名称
#spring:
#  application:
#    name: cloud-consumer-feign-order




eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      #集群
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka

#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    # feign日志  针对哪个接口，以什么级别监控
    per.wsk.springcloud.service.PaymentFeignService: debug